
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastWrapper from "../components/ToastWrapper";
import { CartProvider } from "../contexts/CartContext"; // Adjust path if needed
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <ToastWrapper>
            {children}
          </ToastWrapper>
        </CartProvider>
      </body>
    </html>
  );
}
